// 실행: node tests/engine.test.js
// 현장 시나리오별 기대 판정. 법 개정 시 여기부터 고친다.
'use strict';
var E = require('../assets/engine.js');

var cases = [
  { n: '15세 피해자, 20세 가해자, 동의 하 성관계 → 형법 305조2항',
    i: { date: '2026-10-01', victim: { age: 15 }, offender: { age: 20 }, act: 'r', means: 'none' },
    primary: 'hy305_2_r' },
  { n: '15세 피해자, 18세 가해자, 동의 하 → 305조2항 적용 안 됨',
    i: { date: '2026-10-01', victim: { age: 15 }, offender: { age: 18 }, act: 'r', means: 'none' },
    primary: null, excluded: ['hy305_2_r'] },
  { n: '12세 피해자, 17세 가해자, 동의 → 305조1항 (가해자 나이 무관)',
    i: { date: '2026-10-01', victim: { age: 12 }, offender: { age: 17 }, act: 'r', means: 'none' },
    primary: 'hy305_1_r' },
  { n: '10세 피해자 폭행·협박 강간 → 성폭법 7조1항',
    i: { victim: { age: 10 }, offender: { age: 40 }, act: 'r', means: 'force' },
    primary: 'sp7_1', has: ['ac7_1', 'hy297'] },
  { n: '17세 피해자 강제추행 → 아청법 7조3항',
    i: { victim: { age: 17 }, offender: { age: 30 }, act: 't', means: 'force' },
    primary: 'ac7_3', has: ['hy298'] },
  { n: '만 18세(2026년) 강간 → 아청법 (만 나이 기준)',
    i: { date: '2026-03-01', victim: { birth: '2007-12-01' }, offender: { age: 30 }, act: 'r', means: 'force' },
    primary: 'ac7_1' },
  { n: '2023년 범행, 19세 되는 해 1월1일 지난 만18세 → 구법상 아청법 제외',
    i: { date: '2023-06-01', victim: { birth: '2004-12-01' }, offender: { age: 30 }, act: 'r', means: 'force' },
    primary: 'hy297' },
  { n: '25세 피해자 술 취해 항거불능 간음 → 준강간',
    i: { victim: { age: 25 }, offender: { age: 30 }, act: 'r', means: 'incap' },
    primary: 'hy299_r' },
  { n: '주거침입 후 강제추행 → 3조1항 위헌, 주거침입+강제추행',
    i: { victim: { age: 30 }, offender: { age: 30 }, act: 't', means: 'force', f: { homeInvasion: true } },
    primary: 'hy298', has: ['hy319'], excluded: ['sp3_1'] },
  { n: '주거침입 후 강간 → 3조1항',
    i: { victim: { age: 30 }, offender: { age: 30 }, act: 'r', means: 'force', f: { homeInvasion: true } },
    primary: 'sp3_1' },
  { n: '흉기 휴대 강간 → 특수강간',
    i: { victim: { age: 30 }, offender: { age: 30 }, act: 'r', means: 'force', f: { weapon: true } },
    primary: 'sp4_1' },
  { n: '흉기 휴대 유사강간 → 4조 제외',
    i: { victim: { age: 30 }, offender: { age: 30 }, act: 'p', means: 'force', f: { weapon: true } },
    primary: 'hy297_2', excluded: ['sp4_1'] },
  { n: '친족(30세 피해자) 강간 → 5조1항',
    i: { victim: { age: 30 }, offender: { age: 50 }, act: 'r', means: 'force', f: { kin: true } },
    primary: 'sp5_1' },
  { n: '11세 친족 강간 → 7조1항이 5조보다 무거움',
    i: { victim: { age: 11 }, offender: { age: 50 }, act: 'r', means: 'force', f: { kin: true } },
    primary: 'sp7_1', has: ['sp5_1'] },
  { n: '강간 + 상해 (성인) → 형법 301조',
    i: { victim: { age: 30 }, offender: { age: 30 }, act: 'r', means: 'force', result: 'hurt' },
    primary: 'hy301' },
  { n: '13세 미만 강간 + 치상 → 성폭법 8조1항',
    i: { victim: { age: 9 }, offender: { age: 30 }, act: 'r', means: 'force', result: 'hurt' },
    primary: 'sp8_1' },
  { n: '16세 강간 치상 → 아청법 9조',
    i: { victim: { age: 16 }, offender: { age: 30 }, act: 'r', means: 'force', result: 'hurt' },
    primary: 'ac9' },
  { n: '강간 살해 → 성폭법 9조1항',
    i: { victim: { age: 30 }, offender: { age: 30 }, act: 'r', means: 'force', result: 'murder' },
    primary: 'sp9_1' },
  { n: '지하철 기습추행(성인) → 강제추행 주, 11조 함께',
    i: { victim: { age: 25 }, offender: { age: 40 }, act: 't', means: 'surprise', f: { crowded: true } },
    primary: 'hy298', has: ['sp11'] },
  { n: '강제추행 예비 → 처벌 안 됨',
    i: { victim: { age: 25 }, offender: { age: 40 }, act: 't', means: 'force', stage: 'prep' },
    primary: null, excluded: ['hy298'] },
  { n: '강간 예비 → 형법 305조의3',
    i: { victim: { age: 25 }, offender: { age: 40 }, act: 'r', means: 'force', stage: 'prep' },
    primary: 'hy297' },
  { n: '업무상 위력 추행(성인) → 성폭법 10조1항',
    i: { victim: { age: 25 }, offender: { age: 40 }, act: 't', means: 'deceit', f: { workplace: true } },
    primary: 'sp10_1' },
  { n: '업무상 위력 추행 미수 → 미수 불처벌',
    i: { victim: { age: 25 }, offender: { age: 40 }, act: 't', means: 'deceit', f: { workplace: true }, stage: 'attempt' },
    primary: null, excluded: ['sp10_1'] },
  { n: '14세 위계 간음 → 아청법 7조5항',
    i: { victim: { age: 14 }, offender: { age: 25 }, act: 'r', means: 'deceit' },
    primary: 'ac7_5r', has: ['hy302', 'hy305_2_r'] },
  { n: '14세 궁박 이용 간음 (가해자 25) → 8조의2와 305조2항',
    i: { victim: { age: 14 }, offender: { age: 25 }, act: 'r', means: 'distress' },
    has: ['ac8b_1', 'hy305_2_r'] },
  { n: '17세 장애(변별능력 미약) 동의 간음, 가해자 25 → 아청법 8조1항',
    i: { victim: { age: 17, disability: 'weak' }, offender: { age: 25 }, act: 'r', means: 'none' },
    primary: 'ac8_1' },
  { n: '성인 장애인 강간 → 6조1항',
    i: { victim: { age: 30, disability: 'disabled' }, offender: { age: 40 }, act: 'r', means: 'force' },
    primary: 'sp6_1' },
  { n: '15세 성매수(가해자 30) → 305조2항이 주, 13조 가중',
    i: { victim: { age: 15 }, offender: { age: 30 }, act: 'buying', buyKind: 'r' },
    primary: 'hy305_2_r', has: ['ac13_1'] },
  { n: '17세 성매수 → 아청법 13조1항',
    i: { victim: { age: 17 }, offender: { age: 30 }, act: 'buying', buyKind: 'r' },
    primary: 'ac13_1' },
  { n: '25세 성매매 → 성매매처벌법',
    i: { victim: { age: 25 }, offender: { age: 30 }, act: 'buying', buyKind: 'r' },
    primary: 'pr21' },
  { n: '성인 불법촬영 → 14조1항',
    i: { victim: { age: 25 }, offender: { age: 30 }, act: 'media', sub: 'film' },
    primary: 'sp14_1' },
  { n: '17세 촬영 → 성착취물 제작',
    i: { victim: { age: 17 }, offender: { age: 20 }, act: 'media', sub: 'film' },
    primary: 'ac11_1', has: ['sp14_1'] },
  { n: '딥페이크 소지 2024.9 → 시행 전',
    i: { date: '2024-09-01', victim: { age: 25 }, offender: { age: 30 }, act: 'media', sub: 'possess', synthetic: true },
    primary: null, excluded: ['sp14b_4'] },
  { n: '성인 음란 메시지 → 13조',
    i: { victim: { age: 25 }, offender: { age: 30 }, act: 'online', sub: 'lewd' },
    primary: 'sp13' },
  { n: '15세 그루밍 (가해자 30) → 15조의2',
    i: { victim: { age: 15 }, offender: { age: 30 }, act: 'online', sub: 'groom' },
    primary: 'ac15b' },
  { n: '공연음란',
    i: { victim: {}, offender: { age: 40 }, act: 'exposure' },
    primary: 'hy245', has: ['mo33'] },
  { n: '신고의무자 13세 미만 강제추행 → 18조 가중 위헌 차단',
    i: { victim: { age: 10 }, offender: { age: 40 }, act: 't', means: 'force', f: { reporter: true } },
    primary: 'sp7_3', blockedMod: 'sp7_3' },
  { n: '11세 친족 강제추행 + 신고의무자 → 7조3항 주 (가중이 순위를 바꾸지 않음)',
    i: { victim: { age: 11 }, offender: { age: 45 }, act: 't', means: 'force', f: { kin: true, reporter: true } },
    primary: 'sp7_3', has: ['sp5_2'] },
  { n: '성인과 대가 신체 접촉 → 성매매 아님',
    i: { victim: { age: 25 }, offender: { age: 30 }, act: 'buying', buyKind: 't' },
    primary: null },
  { n: '17세 성착취물 제작 → 공소시효 없음 안내',
    i: { victim: { age: 17 }, offender: { age: 25 }, act: 'media', sub: 'film' },
    primary: 'ac11_1', sol: /공소시효 없음/ },
  { n: '15세 친족 강간 → 공소시효 없음 (아청법 제20조제4항)',
    i: { victim: { age: 15 }, offender: { age: 45 }, act: 'r', means: 'force', f: { kin: true } },
    sol: /공소시효 없음/ },
  { n: '성인 성매매 → 공소시효 특례 안내 없음',
    i: { victim: { age: 25 }, offender: { age: 30 }, act: 'buying', buyKind: 'r' },
    primary: 'pr21', sol: null },
  { n: '2019년 범행, 15세·가해자 20세 동의 → 305조2항 시행 전',
    i: { date: '2019-08-01', victim: { age: 15 }, offender: { age: 20 }, act: 'r', means: 'none' },
    primary: null, excluded: ['hy305_2_r'] },
  { n: '군인→군인 강제추행 → 군형법 함께',
    i: { victim: { age: 22, military: true }, offender: { age: 25, military: true }, act: 't', means: 'force' },
    primary: 'm92_3', has: ['hy298'] },
  { n: '피구금자 간음 → 303조2항',
    i: { victim: { age: 30 }, offender: { age: 40 }, act: 'r', means: 'none', f: { custody: true } },
    primary: 'hy303_2' }
];

var fail = 0;
cases.forEach(function (c) {
  var r = E.evaluate(c.i);
  var errs = [];
  var p = r.primary ? r.primary.id : null;
  if ('primary' in c && p !== c.primary) errs.push('primary=' + p + ' (기대 ' + c.primary + ')');
  (c.has || []).forEach(function (id) { if (!r.hits.some(function (h) { return h.id === id; })) errs.push('누락 ' + id); });
  (c.excluded || []).forEach(function (id) { if (!r.excluded.some(function (h) { return h.id === id; })) errs.push('제외 목록에 없음 ' + id); });
  if ('sol' in c) { if (c.sol === null ? r.sol : !c.sol.test(r.sol || '')) errs.push('공소시효 안내 불일치: ' + r.sol); }
  if (c.blockedMod) { var h = r.hits.filter(function (x) { return x.id === c.blockedMod; })[0]; if (!h || !h.mods.some(function (m) { return m.blocked; })) errs.push('위헌 차단 표시 없음'); }
  if (errs.length) { fail++; console.log('✗ ' + c.n + '\n    ' + errs.join('\n    ') + '\n    hits: ' + r.hits.map(function (h) { return h.id; }).join(', ')); }
  else console.log('✓ ' + c.n);
});
console.log('\n' + (cases.length - fail) + '/' + cases.length + ' 통과');
process.exit(fail ? 1 : 0);
